apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-grafana-stack
  namespace: argocd
spec:
  project: default
  # We are telling ArgoCD to pull directly from the official Helm repository, not your GitHub
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: '60.0.2' 
    chart: kube-prometheus-stack
    helm:
      values: |
        grafana:
          adminPassword: "admin"
          service:
            type: LoadBalancer
        # Add this block to bypass the broken TLS certificates
        prometheusOperator:
          admissionWebhooks:
            enabled: false
          tls:
            enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring # Deploys into a dedicated monitoring namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Tells ArgoCD to create the 'monitoring' namespace if it doesn't exist
      - ServerSideApply=true